### ISSUE TITLE
Tag entities in the text pane

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#49]
**Tag entities not working in the text pane on the right:**

1. if you select text, **the menu appears upon right click** but clicking on one of the tag names doesn’t do anything: the selection disappears (documents tested: Mapping tags and tagging maps, Where are you from, both Chrome and Firefox on Mac)

PC: On Chrome you can right click and still have the text highlighted. On Firefox right-clicking will unhighlight all  highlighted text and you can't tag it. (Cultural Mapping - Mapping tags and tagging maps)

2. if you  **select text and drag onto the entity in the left panel**, text remains unselected and untagged 

PC: On Chrome you can drag the text over to the left panel. On Firefox dragging will unhighlight all text. (Cultural Mapping - Mapping tags and tagging maps.xml)

Mac: in Firefox I cannot drag entities (tagged or untagged) from the text pane to the left-hand panel (doc tested: Mapping tags and tagging Maps); in Chrome I can (doc tested: Where are you from?).

3. **Linking** is missing as an option if you click on an entity in the right-hand/text pane.

**Comment by Thaerious** [comment]
This is something I want to put in, but since there is a way to achieve this (ctrl-m) it's not 'top' priority.  I am removing the bug tag and making it an enhancement.

**Comment by SusanBrown** [comment]
Fine. It would be nice if new additions to the tag lists went into the list alphabetically rather than at the bottom.

Could we remove Tag Selection from the right click menu, since it’s not working? 

In fact, nothing on the right click menu within the text pane is working:

UnTag is still not working: that needs to remain a priority.

Customize Tag is throwing up an exception error:
java.util.NoSuchElementException
- Throwable.java:116
- Cast.java:321
- RuntimeException.java:25
- NoSuchElementException.java:25
- InternalPreconditions.java:59
- AbstractList.java:49
- EntityPanelPopupMenu.java:49
- PopupMenu.java:128
- ClickEvent.java:56
- SimpleEventBus.java:193
- HandlerManager.java:127
- Widget.java:129
- DomEvent.java:125
- Widget.java:177
- Widget.java:163
- DOM.java:1480
- DOMImplStandard.java:317
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
This is a new issue and as such should have it's own ticket.  I'll open up a new ticket for that.

**Comment by Thaerious** [comment]
I'm going to close this ticket and open a new one based specifically on highligh/drag-drop behaviour.
