### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#58]
Some dates on some documents aren't tagged. This happens on both o/s and both browsers. For example, in Cultural Mapping - Forward - V7, no dates are tagged.

**Comment by Thaerious** [comment]
If you mean when it's loaded, then it is out of my hands.  The tagging is done by the Stanford toolset.  If you mean the tags don't stay then it becomes an issue.  Hopefully retraining the NER (from stanford) will help, but that won't happen for some time.

**Comment by cutic** [comment]
Yes, when it is loaded, some documents do not have the dates that appear in them tagged (some documents have none of the dates tagged, some have all of them tagged). If the problem is the Stanford toolset, that is fine, dates can be tagged by hand. 

The problem in NERVE now is that you cannot tag entities in the text pane, so we can't test to see if the tags actually stay there or not. When you highlight an entity you want to tag, and click on Tag Selection - Date in the drop down menu, it doesn't do anything. And because you can't tag it in the text panel you can't drag it into the left hand panel either.

**Comment by Thaerious** [comment]
Ctrl-M Creates new tags, I've been desperately trying to get "Tag" to also create new tags as that makes the most sense, but other issues take priority.

**Comment by cutic** [comment]
Yes, ctrl-m works.

**Comment by SusanBrown** [comment]
OK got it. First you have to tag the entity with CTRL M (why M?) and then drag it over to the entity you want to tag it with. That's great, though not very intuitive. 

However, if there is no existing entity with which you want to merge it, you are stuck. Will make this a separate issue.

Anita, I've made the point you made above about tagging by dragging and dropping into a separate issue. We should try to do that as much as possible.
