### ISSUE TITLE
Hidden Options Bar

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#73]
If you open a file with a long file name, the options bar at the top of the page will disappear. This inhibits saving work, downloading, etc so is more pressing than if it were just a graphics issue.

![image](https://cloud.githubusercontent.com/assets/17013275/15410990/e9090b26-1dea-11e6-856c-1003f89c4a2a.png)

**Comment by cutic** [comment]
I agree. If you make your browser window bigger you will be able to see the whole thing.

**Comment by Thaerious** [comment]
The essential for immediate use tag is redundant.  I've taken it off and replaced it with the high priority bug tag, with implies it's essential.

**Comment by Thaerious** [comment]
I have changed the formatting so that two things are different.  1) The title text no longer wraps.  This means the super long titles will be cut off.  There has to be an upper limit of some sort.  2) resizing the screen not longer smushes the left hand NERVE info box (the purple one) which was causing the menu to be displayed behind the app, thus hiding it.  NOTE*** you have to empty your cache for this update to work.

**Comment by cutic** [comment]
Looks much better now. Only on my 15 inch screen I have problems seeing email@address part. 

![title email](https://cloud.githubusercontent.com/assets/17013268/15440953/6fae9754-1e95-11e6-8de0-f84eeed2a26d.png)

I understand this is not a priority, but just thought I'd add it here.

**Comment by Thaerious** [comment]
I'll have to code something to dynamically change the font size / area size for different screen dimensions.  This is going onto the back burner for now.
