### ISSUE TITLE
Crooked Ribs generating exception error when opened

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#9]
xClose
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'data' of undefined
(TypeError) : Cannot read property 'data' of undefined
- Exceptions.java:36
- TaggedEntity.java:82
- TECDropPanel.java:31
- AutoTagger.java:132
- CustomMenuButtons.java:205
- FileOperations.java:71
- FileOperations.java:70
- RequestCallbackAdapter.java:230
- Request.java:250
- RequestBuilder.java:412
- XMLHttpRequest.java:329
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
The problem was... When a tagged element had no text the TaggedElement class would fail to parse.  This document is using "Title" in two different ways, one as a placeholder for the document title and second as a title in the biblio.  I have made it so that empty tags are not considered tagged entities and are simply pushed through.  However, this document does not strictly adhere to the Orlando spec, note the lower case xml tags.  As it currently sits when this is saved those tags will become upper case.
